### ISSUE TITLE
Build failure with utf8-string

### ISSUE THREAD

**Issue by achudnov** [GaloisInc/http-server#6]
Iavor (@yav),
The recent release of `utf8-string` (http://hackage.haskell.org/package/utf8-string) does not include `System.IO.UTF8`, imported from `Network.HTTP.Server.Logger`. I've submitted a pull request (#7) to with a restricted bound on `utf8-string` that solves the build problem "here and now". But, I think, a better long-term solution would be to use `hPutStrLn` from `System.IO`, which, I think, has supported UTF8 for a while (and that was the reason for removing the API in question from `utf8-string`). That should also be a straightforward patch that I can apply, test and submit if you like.

Note: you don't even need to roll out a new version since you can now edit package dependencies for released packages directly on Hackage.

**Comment by yav** [comment]
This should be fixed now.

**Comment by achudnov** [comment]
Thanks!
